### ISSUE TITLE
./scripts/setup_tools.sh error on MAC M1

### ISSUE THREAD

**Issue by lgdu** [jbush001/NyuziProcessor#205] opened 2022-11-02 08:21 UTC
Hi,
I got these errors when i run ./scripts/setup_tools.sh on MAC M1 Platform.
```
CMake Error at /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/ExternalProject.cmake:2474:EVAL:2 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:llvm-ranlib>

  Target "llvm-ranlib" is not an executable or library.
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/ExternalProject.cmake:2474 (cmake_language)
  cmake/modules/LLVMExternalProjectUtils.cmake:239 (ExternalProject_Add_Step)
  runtimes/CMakeLists.txt:216 (llvm_ExternalProject_Add)
  runtimes/CMakeLists.txt:275 (builtin_default_target)


CMake Error at /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/ExternalProject.cmake:2474:EVAL:2 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:llvm-strip>

  Target "llvm-strip" is not an executable or library.
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/ExternalProject.cmake:2474 (cmake_language)
  cmake/modules/LLVMExternalProjectUtils.cmake:239 (ExternalProject_Add_Step)
  runtimes/CMakeLists.txt:216 (llvm_ExternalProject_Add)
  runtimes/CMakeLists.txt:275 (builtin_default_target)


CMake Error at /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/ExternalProject.cmake:2474:EVAL:2 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:llvm-ranlib>

  Target "llvm-ranlib" is not an executable or library.
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/ExternalProject.cmake:2474 (cmake_language)
  cmake/modules/LLVMExternalProjectUtils.cmake:239 (ExternalProject_Add_Step)
  runtimes/CMakeLists.txt:216 (llvm_ExternalProject_Add)
  runtimes/CMakeLists.txt:275 (builtin_default_target)


CMake Error at /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/ExternalProject.cmake:2474:EVAL:2 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:llvm-strip>

  Target "llvm-strip" is not an executable or library.
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/ExternalProject.cmake:2474 (cmake_language)
  cmake/modules/LLVMExternalProjectUtils.cmake:239 (ExternalProject_Add_Step)
  runtimes/CMakeLists.txt:216 (llvm_ExternalProject_Add)
  runtimes/CMakeLists.txt:275 (builtin_default_target)

```

**Comment by jbush001** [comment] 2022-11-04 02:52
Looks like the same issue as #204, except that was on Linux and this is on Mac. I'm guessing perhaps an incompatible change in a newer version of cmake or some other tool.

**Comment by jbush001** [comment] 2022-12-03 15:55
duplicate of #204

**Closed by jbush001** 2022-12-03 15:55 UTC
