### ISSUE TITLE
TARGET_FILE:llvm-strip : build error 

### ISSUE THREAD

**Issue by xingfeT** [jbush001/NyuziProcessor#207] opened 2023-07-08 04:08 UTC
CMake Error at /usr/share/cmake/Modules/ExternalProject.cmake:2373:EVAL:2 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:llvm-ranlib>

  Target "llvm-ranlib" is not an executable or library.
Call Stack (most recent call first):
  /usr/share/cmake/Modules/ExternalProject.cmake:2373 (cmake_language)
  cmake/modules/LLVMExternalProjectUtils.cmake:239 (ExternalProject_Add_Step)
  runtimes/CMakeLists.txt:216 (llvm_ExternalProject_Add)
  runtimes/CMakeLists.txt:275 (builtin_default_target)

CMake Error at /usr/share/cmake/Modules/ExternalProject.cmake:2373:EVAL:2 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:llvm-strip>

  Target "llvm-strip" is not an executable or library.
Call Stack (most recent call first):
  /usr/share/cmake/Modules/ExternalProject.cmake:2373 (cmake_language)
  cmake/modules/LLVMExternalProjectUtils.cmake:239 (ExternalProject_Add_Step)
  runtimes/CMakeLists.txt:216 (llvm_ExternalProject_Add)
  runtimes/CMakeLists.txt:275 (builtin_default_target)

CMake Warning (dev) at cmake/modules/TableGen.cmake:72 (add_custom_command):
  Policy CMP0116 is not set: Ninja generators transform DEPFILEs from
  add_custom_command().  Run "cmake --help-policy CMP0116" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.
Call Stack (most recent call first):
  unittests/Option/CMakeLists.txt:8 (tablegen)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by jbush001** [comment] 2023-07-09 05:25
duplicate of #204

**Closed** 2023-07-09 05:26 UTC
